import { Color, Vec2 } from '../../types';

export const defaultMapShaderUniforms = {
  uEnablePatterns: false,
  uPatternSize: 90,
  uEnablePulsations: true,
  uHoveredProvinceColor: [0, 0, 0] as Color,
  uPulsationPeriod: 2,
  uPulsationIntensity: 0.2,
  uEnableHover: true,
  uVisualizationMethod: 3,
  uDisplayBlankMap: false,
  uBlendFactor: 0.81,
  uContrast: 3.2,
  uMiddleGray: 0.65,
  uGrayscaleBlendFactor: 1,
  uHoverVisualizationMethod: 3,
  uHoverBlendFactor: 1,
  uBlendFactorSecondary: 1,
  uHoverGrayscaleBlendFactor: 0.83,
  uUseAverageGrayWeights: false,
  uGlowRadius: 0.01,
  uGlowPulsationRadius: 0.0055,
  uGlowPulsationPeriod: 5,
  uGlowIntensity: 1.45,
  uGlowType: 1,
  uUseOuterContour: false,
  uUseContourAntialiasing: true,
  uContourIntensity: 1.1,
  uContourLuminosity: 0.19,
  uInnerContourSize: 0.0035,
  uOuterContourSize: 0.002,
  uMouseIlluminationRadius: 0.155,
  uMouseIlluminationIntensity: 0.1,
  uEnableMouseIllumination: false,
  uDebugValue1: 0.5,
  uDebugValue2: 1,
  uDebugToggle1: true,
  uDebugToggle2: false,
  uEnableGlow: true,
  uBorderMapOpacity: 1,
  uUseColoredBorders: false,
  uEnableContour: true,
  uContourOpacity: 1,
  uInnerContourSample: 32,
  uGlowAndOuterContourSample: 32,
  uUseUniformColorFetching: false,
  uGlowColor: [0.4, 0.4, 0.4] as Color,
  uUseJunctionAntialiasing: true,
  uJunctionAntialiasingSize: 0.04
};

export const baseDefaultWaterUniforms = {
  uEnableWaterAnimation: true,
  uEnableNoise1: true,
  uDisplayNoise1: false,
  uMaxOffset1: 0.1,
  uNoiseScale1: 12,
  uSpeed1: 0.06,
  uTextureShift1: [-0.1, 0.05] as Vec2,
  uUseRandomizedNoise1: false,
  uUseEasing1: false,
  uUseNoiseIllumination1: false,
  uNoiseIlluminationIntensity1: 0,
  uUseNoiseDeformation1: true,
  uEnableNoise2: true,
  uDisplayNoise2: false,
  uMaxOffset2: 0.022,
  uNoiseScale2: 1.8,
  uSpeed2: 0.09,
  uTextureShift2: [0.1, 0.1] as Vec2,
  uUseRandomizedNoise2: true,
  uUseEasing2: false,
  uUseNoiseIllumination2: true,
  uNoiseIlluminationIntensity2: 1,
  uUseNoiseDeformation2: true,
  uUseDebug: true,
  uDebugIndex: 0,
  uEnableNoise3: true,
  uDisplayNoise3: false,
  uMaxOffset3: 0.008,
  uNoiseScale3: 0.45,
  uSpeed3: 0.24,
  uTextureShift3: [0.1, 0.1] as Vec2,
  uUseRandomizedNoise3: true,
  uUseEasing3: false,
  uUseNoiseIllumination3: true,
  uNoiseIlluminationIntensity3: 0.8,
  uUseNoiseDeformation3: true
};

export const baseDefaultMouseUniforms = {
  uMouseIlluminationRadius: defaultMapShaderUniforms.uMouseIlluminationRadius,
  uMouseIlluminationIntensity: defaultMapShaderUniforms.uMouseIlluminationIntensity,
  uEnableMouseIllumination: true,
  uEnableWaterWaveIllumination: true,
  uWaterWaveIlluminationIntensity: 4
};
