import { Color, Vec2 } from '../../types';

export const defaultMapShaderUniforms = {
  uEnablePatterns: false,
  uPatternSize: 90,
  uEnablePulsations: false,
  uHoveredProvinceColor: [0, 0, 0] as Color,
  uPulsationPeriod: 2,
  uPulsationIntensity: 0.2,
  uEnableHover: true,
  uVisualizationMethod: 3,
  uDisplayBlankMap: false,
  uBlendFactor: 0.81,
  uContrast: 3.2,
  uMiddleGray: 0.65,
  uGrayscaleBlendFactor: 1,
  uHoverVisualizationMethod: 3,
  uHoverBlendFactor: 0.9,
  uBlendFactorSecondary: 1,
  uHoverGrayscaleBlendFactor: 0.83,
  uUseAverageGrayWeights: false,
  uGlowRadius: 0.02,
  uGlowPulsationRadius: 0.055,
  uGlowPulsationPeriod: 5,
  uGlowIntensity: 2.45,
  uUseOuterContour: false,
  uUseContourAntialiasing: true,
  uContourIntensity: 1.1,
  uContourLuminosity: 0.19,
  uInnerContourSize: 0.0035,
  uOuterContourSize: 0.002,
  uMouseIlluminationRadius: 0.2,
  uMouseIlluminationIntensity: 0.07,
  uEnableMouseIllumination: true,
  uEnableGlow: true,
  uBorderMapOpacity: 1,
  uUseColoredBorders: false,
  uEnableContour: true,
  uContourOpacity: 1,
  uInnerContourSample: 32,
  uGlowAndOuterContourSample: 32,
  uUseUniformColorFetching: true,
  uGlowColor: [0.4, 0.4, 0.4] as Color,
  uUseJunctionAntialiasing: true,
  uJunctionAntialiasingSize: 0.04,
  uVisualitionMode: 0
};

export const baseDefaultMouseUniforms = {
  uMouseIlluminationRadius: defaultMapShaderUniforms.uMouseIlluminationRadius,
  uMouseIlluminationIntensity: defaultMapShaderUniforms.uMouseIlluminationIntensity,
  uEnableMouseIllumination: true
};
