name: Deploy React/Vite to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci
        
      - name: Update Vite Config
        run: |
          echo "import { defineConfig } from 'vite';
          import react from '@vitejs/plugin-react';

          export default defineConfig({
            plugins: [react()],
            base: '/phaser-map-poc/',
            publicDir: 'public',
            resolve: {
              alias: {
                '@': '/src',
                '@phaser': '/src/phaser',
                '@map': '/src/phaser/map'
              }
            },
            build: {
              outDir: 'dist'
            },
            server: {
              port: 3000
            },
            assetsInclude: ['**/*.frag']
          });" > vite.config.ts

      - name: Build
        run: npm run build
        env:
          NODE_ENV: production

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4